#!/bin/bash
# Setup and usage guide for Document Extraction System

echo "=========================================="
echo "Document Extraction System - Setup Complete"
echo "=========================================="
echo ""
echo "✅ Virtual environment created at: venv/"
echo "✅ All dependencies installed successfully"
echo "✅ Examples verified working"
echo ""
echo "=========================================="
echo "Quick Start Commands"
echo "=========================================="
echo ""
echo "1. Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "2. Run examples:"
echo "   python3 examples.py"
echo ""
echo "3. Extract a PDF to JSON:"
echo "   python3 extract.py --input your_document.pdf --output output.json"
echo ""
echo "4. Extract with verbose logging:"
echo "   python3 extract.py --input document.pdf --verbose"
echo ""
echo "=========================================="
echo "Project Structure"
echo "=========================================="
echo ""
echo "✓ extractor/              - Core extraction modules"
echo "  ├── __init__.py         - Package initialization"
echo "  ├── config.py           - Schemas and configuration"
echo "  ├── json_formatter.py   - JSON handling"
echo "  ├── ocr_handler.py      - OCR processing"
echo "  └── pdf_processor.py    - PDF extraction"
echo ""
echo "✓ extract.py             - Main CLI tool"
echo "✓ examples.py            - Usage examples"
echo "✓ test_extraction.py     - Unit tests"
echo "✓ requirements.txt       - Dependencies"
echo "✓ README.md              - Full documentation"
echo "✓ QUICKSTART.md          - Quick reference"
echo ""
echo "=========================================="
echo "Next Steps"
echo "=========================================="
echo ""
echo "1. For BIO datasets:"
echo "   python3 extract.py --input ../Datasets/BIO/document.pdf"
echo ""
echo "2. For Patents datasets:"
echo "   python3 extract.py --input ../Datasets/Patents/patent.pdf"
echo ""
echo "3. Check output in generated .json files"
echo ""
echo "=========================================="
